#define MEM_START_ADDR      0x00000000
#define MEM_END_ADDR        0x07FFFFFF


#define STACK_START_ADDR    0x00100000
#define STACK_SIZE          0x00100000  // 1MB
#define USR_STACK_START     (STACK_START_ADDR)
#define SYS_STACK_START     (STACK_START_ADDR)
#define SVC_STACK_START     (STACK_START_ADDR + (STACK_SIZE * 2))
#define IRQ_STACK_START     (STACK_START_ADDR + (STACK_SIZE * 3))
#define FIQ_STACK_START     (STACK_START_ADDR + (STACK_SIZE * 4))
#define ABT_STACK_START     (STACK_START_ADDR + (STACK_SIZE * 5))
#define UND_STACK_START     (STACK_START_ADDR + (STACK_SIZE * 6))
#define TASK_STACK_START    (STACK_START_ADDR + (STACK_SIZE * 7))

#define USR_STACK_SIZE      (SVC_STACK_START - USR_STACK_START)
#define SYS_STACK_SIZE      (SVC_STACK_START - SYS_STACK_START)
#define SVC_STACK_SIZE      (IRQ_STACK_SIZE - SVC_STACK_SIZE)
#define IRQ_STACK_SIZE      (FIQ_STACK_SIZE - IRQ_STACK_SIZE)
#define FIQ_STACK_SIZE      (ABT_STACK_SIZE - FIQ_STACK_SIZE)
#define ABT_STACK_SIZE      (UND_STACK_SIZE - ABT_STACK_SIZE)
#define UND_STACK_SIZE      (TASK_STACK_SIZE - UND_STACK_SIZE)
#define TASK_STACK_SIZE     (GLOBAL_ADDR_START - TASK_STACK_SIZE)

#define INST_START_ADDR     0
#define GLOBAL_ADDR_START   0x04800000
#define DALLOC_ADDR_START   0x04900000

#define INST_MEM_SIZE       (USR_STACK_START - INST_START_ADDR)
#define GLOBAL_MEM_SIZE     (DALLOC_ADDR_START - GLOBAL_ADDR_START)
#define DALLOC_MEM_SIZE     (MEM_END_ADDR - DALLOC_ADDR_START)

#define USR_STACK_TOP       (USR_STACK_START + (USR_STACK_SIZE - 4))
#define SYS_STACK_TOP       (SYS_STACK_START + (SYS_STACK_SIZE - 4))
#define SVC_STACK_TOP       (SVC_STACK_START + (SVC_STACK_SIZE - 4))
#define IRQ_STACK_TOP       (IRQ_STACK_START + (IRQ_STACK_SIZE - 4))
#define FIQ_STACK_TOP       (FIQ_STACK_START + (FIQ_STACK_SIZE - 4))
#define ABT_STACK_TOP       (ABT_STACK_START + (ABT_STACK_SIZE - 4))
#define UND_STACK_TOP       (UND_STACK_START + (UND_STACK_SIZE - 4))
#define TASK_STACK_TOP      (TASK_STACK_START + (TASK_STACK_SIZE - 4))